name: Build and Release
permissions:
  contents: write

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.3

      # Cache Go modules
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Download dependencies and update go.sum
      - name: Download dependencies
        run: go mod tidy && go mod download

      # Build the project
      - name: Build binary
        run: go build -o darkThroneAutomate .

      # Verify the binary exists
      - name: Verify binary
        run: ls -l darkThroneAutomate

      # Upload the binary as an artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: darkThroneAutomate
          path: darkThroneAutomate

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Download the artifact
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: darkThroneAutomate

      # Create a GitHub release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: darkThroneAutomate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
